#!/bin/bash

NOMINATIM_PASSWORD="${NOMINATIM_PASSWORD:-$PGPASSWORD}"
NOMINATIM_DATABASE_DSN="${NOMINATIM_DATABASE_DSN:-host=$PGHOST dbname=$PGDATABASE user=$PGUSER password=$PGPASSWORD}"

export_config() {
  export NOMINATIM_TOKENIZER=icu
  export NOMINATIM_DATABASE_DSN="$NOMINATIM_DATABASE_DSN"

  export NOMINATIM_IMPORT_STYLE="${IMPORT_STYLE:-full}"

  if [ "${FLATNODE_FILE}" != "" ]; then
    export NOMINATIM_FLATNODE_FILE="${PROJECT_DIR}/${FLATNODE_FILE}"
  fi

  if [ "$REPLICATION_URL" != "" ]; then
    export NOMINATIM_REPLICATION_URL="$REPLICATION_URL"

    export NOMINATIM_REPLICATION_UPDATE_INTERVAL="${REPLICATION_UPDATE_INTERVAL:-86400}"
    export NOMINATIM_REPLICATION_RECHECK_INTERVAL="${REPLICATION_RECHECK_INTERVAL:-900}"
  fi

  if [ "$IMPORT_TIGER_ADDRESSES" = "true" ] || [ -f "$IMPORT_TIGER_ADDRESSES" ]; then
    export NOMINATIM_USE_US_TIGER_DATA=yes
  fi
}
